steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform init -upgrade -chdir=GCP/create-ha-vpn-comm"]
  - name: 'bash'
    args: ['pwd']    
  - name: 'bash'
    args: ["-c","ls -ltr"]    
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform plan -chdir=GCP/create-ha-vpn-comm -out=plan.out"]    
