steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCP/create-ha-vpn-comm init -upgrade "]
  - name: 'bash'
    args: ['pwd']    
  - name: 'bash'
    args: ["-c","ls -ltr"]    
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args: ["-c","terraform -chdir=GCP/create-ha-vpn-comm plan  -out=plan.out"]    
